### ISSUE TITLE
Remote files in Nova not being tracked

### ISSUE THREAD

**Issue by ckerr15** [wakatime/WakaTime.novaextension#2] opened 2020-10-13 14:05 UTC
Hello!

I think there may be an issue with the new Nova plugin where it "ignores" heartbeats that are triggered by editing a remote file. I'm using Nova's built-in SFTP editor, and editing files in Nova through the Nova file browser.

Here's what I can see in my ~/wakatime.log:
`{"now": "2020/10/13 14:53:16 +0100", "version": "13.0.7", "plugin": "nova/1.2 nova-wakatime/1.0.3", "time": 1602597196.566935, "caller": "wakatime/main.py", "lineno": 68, "is_write": true, "file": "/var/www/-redacted-/html/wp-content/themes/-redacted-/searchform.php", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}`

Also:
`{"now": "2020/10/13 15:04:30 +0100", "version": "13.0.7", "plugin": "nova/1.2 nova-wakatime/1.0.3", "time": 1602597870.3397892, "caller": "wakatime/main.py", "lineno": 68, "file": "/var/www/-redacted-/html/wp-content/themes/-redacted-/searchform.php", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}`

Is there any way that your plugin can be patched to support remote file tracking too? Wakatime for Coda 2 did this, would be great to see it in Nova too. :)

Thanks!
Callum

**Comment by alanhamlett** [comment] 2020-10-13 14:32
This is different from wakatime/coda-wakatime#1, because there the project wasn't detected but the time still logged. Here we need to find the temporary buffer file on the local filesystem and pass that into wakatime-cli. Otherwise, if the file it gets doesn't exist locally then it just exits without logging any time.

Also, this is a duplicate of #1.

**Comment by ckerr15** [comment] 2020-10-13 14:38
Apologies for the duplicate, I completely forgot to check! If you want any extra info from me, please do let me know.

Thanks!

**Comment by EllieLockhart** [comment] 2020-11-22 16:58
Also having this issue!

**Comment by EllieLockhart** [comment] 2020-11-22 21:32
Incidentally, I could try to debug/fix this myself, but I'd need confirmation it's an issue with the plugin and not something deeper. Like, I suspect VSCode (which I so want to stop using) avoids this by installing what amounts to code-server on the remote host, whereas as far as I can tell, Nova just makes an SSH connection and does everything else in the local OS X installation. If VSCode's way is the only solution, I worry this may not be solvable, at least for non-OS X remotes.

**Comment by EllieLockhart** [comment] 2020-11-22 21:35
A thought: could the plugin be adjusted to make a local copy of the file or even a dummy file and send that file path to the plugin for heartbeats?

**Comment by alanhamlett** [comment] 2020-11-24 00:21
> could the plugin be adjusted to make a local copy of the file or even a dummy file and send that file path to the plugin for heartbeats?

Good idea, that would work! We'd need to detect a remote vs local file, then copy the [first 512000 bytes](https://github.com/wakatime/wakatime/blob/bb3c1616d47f313ca03629fe26368059037ba340/wakatime/stats.py#L294) of the file into a local temp file before executing the wakatime-cli.

I'll get this implemented and release a new version today.

**Comment by alanhamlett** [comment] 2020-11-24 08:32
Fixed with 649f560d5040749b21e30588451fb68447cab314 and released just now in v2.0.0.

**Closed as completed by alanhamlett** 2020-11-24 08:32 UTC
